# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oRFJbqdK-yehmPtVRGD4w3KT3vA61Cu_
"""

from fastapi import FastAPI
from pydantic import BaseModel
from ml.model import load_model
model = None
app = FastAPI()

class TempResponse(BaseModel):
    temp: float


# create a route
@app.get("/")
def index():
    return {"text": "Prediction stars temperature"}


# Register the function to run during startup
@app.on_event("startup")
def startup_event():
    global model
    model = load_model()


# Your FastAPI route handlers go here
@app.get("/predict")
def predict_temp(luminosity:float, radius:float, abs_magnitude:float, star_type:int,star_color:str):
    temp_value = model(luminosity, radius, abs_magnitude, star_type, star_color)
    response = TempResponse(temp=float(temp_value))
    return response
